---
version: "3.1"

services:
  myjenkins:
    image: jenkins
    ports:
      - 8989:8080      

  qaserver:
    image: tomcat      
    ports:
      - 9999:8080     
    links:
      - myjenkins:jenkins
  prodserver:    
    image: tomcat
    ports:
      - 7777:8080       
    links:
      - myjenkins:jenkins     
...         

