version: "3.1"

services:        

  mywordpress:
    image: wordpress
    ports:
      - 8080:80

  mydb:
    image: mongo      
    environment:
      MONGO_INITDB_ROOT_USERNAME: root      
      MONGO_INITDB_ROOT_PASSWORD: example
    links:
      - mywordpress:wordpress       
