version: "3"

services:
  mydb:
   image: mysql      
   environment:
     MYSQL_ROOT_PASSWORD: siva

  apache:
   image: httpd      
   ports:
     - 5959:80
   links:
     - mydb:mysql      
       
  php:
   image: php:7.1-apache       
   ports:
     - 6969:80
   links:
     - mydb:mysql        
     - apache:httpd  

